DROP DATABASE IF EXISTS bigdata;
CREATE DATABASE bigdata;
USE bigdata;

CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT NOT NULL,
  first_name VARCHAR(40) NOT NULL,
  last_name VARCHAR(40) NOT NULL,
  email VARCHAR(80) NOT NULL,
  password VARCHAR(40) NOT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS expense (
  id INT AUTO_INCREMENT NOT NULL,
  user_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  price FLOAT NOT NULL,
  description TEXT DEFAULT NULL ,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS category (
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS expense_category (
  id INT AUTO_INCREMENT NOT NULL,
  expense_id INT NOT NULL,
  category_id INT NOT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`expense_id`) REFERENCES `expense` (`id`),
  FOREIGN KEY (`category_id`) REFERENCES `category` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `user` VALUES (1, "Peter", "Skurski", "piotr@email.pl", "1234", DEFAULT, DEFAULT);

INSERT INTO `expense` VALUES (1, 1, "Car", 35000.99, "Beatiful car...", DEFAULT, DEFAULT);
INSERT INTO `expense` VALUES (2, 1, "Phone", 780.99, "Huawei P8 Lite", DEFAULT, DEFAULT);
INSERT INTO `expense` VALUES (3, 1, "Guitar", 400.00, "Guitar with amplifier and stuff.", DEFAULT, DEFAULT);

INSERT INTO `category` VALUES (1, "Vehicles", "All vehicles that you have.", DEFAULT, DEFAULT);
INSERT INTO `category` VALUES (2, "Fun", "All used for fun.", DEFAULT, DEFAULT);

INSERT INTO `expense_category` VALUES (1, 1, 1, DEFAULT, DEFAULT);
INSERT INTO `expense_category` VALUES (2, 2, 2, DEFAULT, DEFAULT);
INSERT INTO `expense_category` VALUES (3, 3, 2, DEFAULT, DEFAULT);